version: '3.8'

services:
  rag-chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    container_name: rag-chatbot
    
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
